// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-v2/internal/domain/ent/conversation"
	"chat-v2/internal/domain/ent/conversationparticipant"
	"chat-v2/internal/domain/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ConversationParticipant is the model entity for the ConversationParticipant schema.
type ConversationParticipant struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID uuid.UUID `json:"conversation_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConversationParticipantQuery when eager-loading is set.
	Edges        ConversationParticipantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConversationParticipantEdges holds the relations/edges for other nodes in the graph.
type ConversationParticipantEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *Conversation `json:"conversation,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationParticipantEdges) ConversationOrErr() (*Conversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: conversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationParticipantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConversationParticipant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversationparticipant.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case conversationparticipant.FieldID, conversationparticipant.FieldConversationID, conversationparticipant.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConversationParticipant fields.
func (_m *ConversationParticipant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversationparticipant.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case conversationparticipant.FieldConversationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value != nil {
				_m.ConversationID = *value
			}
		case conversationparticipant.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case conversationparticipant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConversationParticipant.
// This includes values selected through modifiers, order, etc.
func (_m *ConversationParticipant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the ConversationParticipant entity.
func (_m *ConversationParticipant) QueryConversation() *ConversationQuery {
	return NewConversationParticipantClient(_m.config).QueryConversation(_m)
}

// QueryUser queries the "user" edge of the ConversationParticipant entity.
func (_m *ConversationParticipant) QueryUser() *UserQuery {
	return NewConversationParticipantClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ConversationParticipant.
// Note that you need to call ConversationParticipant.Unwrap() before calling this method if this ConversationParticipant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConversationParticipant) Update() *ConversationParticipantUpdateOne {
	return NewConversationParticipantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConversationParticipant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConversationParticipant) Unwrap() *ConversationParticipant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConversationParticipant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConversationParticipant) String() string {
	var builder strings.Builder
	builder.WriteString("ConversationParticipant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("conversation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConversationParticipants is a parsable slice of ConversationParticipant.
type ConversationParticipants []*ConversationParticipant
