// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-v2/internal/domain/ent/conversation"
	"chat-v2/internal/domain/ent/conversationparticipant"
	"chat-v2/internal/domain/ent/message"
	"chat-v2/internal/domain/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConversationUpdate is the builder for updating Conversation entities.
type ConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdate) Where(ps ...predicate.Conversation) *ConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *ConversationUpdate) SetType(v conversation.Type) *ConversationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableType(v *conversation.Type) *ConversationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ConversationUpdate) SetTitle(v string) *ConversationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableTitle(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *ConversationUpdate) ClearTitle() *ConversationUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ConversationUpdate) SetDisplayName(v string) *ConversationUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableDisplayName(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ConversationUpdate) ClearDisplayName() *ConversationUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetCanonicalName sets the "canonical_name" field.
func (_u *ConversationUpdate) SetCanonicalName(v string) *ConversationUpdate {
	_u.mutation.SetCanonicalName(v)
	return _u
}

// SetNillableCanonicalName sets the "canonical_name" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCanonicalName(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetCanonicalName(*v)
	}
	return _u
}

// ClearCanonicalName clears the value of the "canonical_name" field.
func (_u *ConversationUpdate) ClearCanonicalName() *ConversationUpdate {
	_u.mutation.ClearCanonicalName()
	return _u
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ConversationUpdate) AddMessageIDs(ids ...uuid.UUID) *ConversationUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ConversationUpdate) AddMessages(v ...*Message) *ConversationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddParticipantIDs adds the "participants" edge to the ConversationParticipant entity by IDs.
func (_u *ConversationUpdate) AddParticipantIDs(ids ...uuid.UUID) *ConversationUpdate {
	_u.mutation.AddParticipantIDs(ids...)
	return _u
}

// AddParticipants adds the "participants" edges to the ConversationParticipant entity.
func (_u *ConversationUpdate) AddParticipants(v ...*ConversationParticipant) *ConversationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipantIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdate) Mutation() *ConversationMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ConversationUpdate) ClearMessages() *ConversationUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ConversationUpdate) RemoveMessageIDs(ids ...uuid.UUID) *ConversationUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ConversationUpdate) RemoveMessages(v ...*Message) *ConversationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearParticipants clears all "participants" edges to the ConversationParticipant entity.
func (_u *ConversationUpdate) ClearParticipants() *ConversationUpdate {
	_u.mutation.ClearParticipants()
	return _u
}

// RemoveParticipantIDs removes the "participants" edge to ConversationParticipant entities by IDs.
func (_u *ConversationUpdate) RemoveParticipantIDs(ids ...uuid.UUID) *ConversationUpdate {
	_u.mutation.RemoveParticipantIDs(ids...)
	return _u
}

// RemoveParticipants removes "participants" edges to ConversationParticipant entities.
func (_u *ConversationUpdate) RemoveParticipants(v ...*ConversationParticipant) *ConversationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipantIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := conversation.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Conversation.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(conversation.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(conversation.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(conversation.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.CanonicalName(); ok {
		_spec.SetField(conversation.FieldCanonicalName, field.TypeString, value)
	}
	if _u.mutation.CanonicalNameCleared() {
		_spec.ClearField(conversation.FieldCanonicalName, field.TypeString)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipantsIDs(); len(nodes) > 0 && !_u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationUpdateOne is the builder for updating a single Conversation entity.
type ConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMutation
}

// SetType sets the "type" field.
func (_u *ConversationUpdateOne) SetType(v conversation.Type) *ConversationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableType(v *conversation.Type) *ConversationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ConversationUpdateOne) SetTitle(v string) *ConversationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableTitle(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *ConversationUpdateOne) ClearTitle() *ConversationUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ConversationUpdateOne) SetDisplayName(v string) *ConversationUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableDisplayName(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ConversationUpdateOne) ClearDisplayName() *ConversationUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetCanonicalName sets the "canonical_name" field.
func (_u *ConversationUpdateOne) SetCanonicalName(v string) *ConversationUpdateOne {
	_u.mutation.SetCanonicalName(v)
	return _u
}

// SetNillableCanonicalName sets the "canonical_name" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCanonicalName(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetCanonicalName(*v)
	}
	return _u
}

// ClearCanonicalName clears the value of the "canonical_name" field.
func (_u *ConversationUpdateOne) ClearCanonicalName() *ConversationUpdateOne {
	_u.mutation.ClearCanonicalName()
	return _u
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ConversationUpdateOne) AddMessageIDs(ids ...uuid.UUID) *ConversationUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ConversationUpdateOne) AddMessages(v ...*Message) *ConversationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddParticipantIDs adds the "participants" edge to the ConversationParticipant entity by IDs.
func (_u *ConversationUpdateOne) AddParticipantIDs(ids ...uuid.UUID) *ConversationUpdateOne {
	_u.mutation.AddParticipantIDs(ids...)
	return _u
}

// AddParticipants adds the "participants" edges to the ConversationParticipant entity.
func (_u *ConversationUpdateOne) AddParticipants(v ...*ConversationParticipant) *ConversationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipantIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdateOne) Mutation() *ConversationMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ConversationUpdateOne) ClearMessages() *ConversationUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ConversationUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *ConversationUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ConversationUpdateOne) RemoveMessages(v ...*Message) *ConversationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearParticipants clears all "participants" edges to the ConversationParticipant entity.
func (_u *ConversationUpdateOne) ClearParticipants() *ConversationUpdateOne {
	_u.mutation.ClearParticipants()
	return _u
}

// RemoveParticipantIDs removes the "participants" edge to ConversationParticipant entities by IDs.
func (_u *ConversationUpdateOne) RemoveParticipantIDs(ids ...uuid.UUID) *ConversationUpdateOne {
	_u.mutation.RemoveParticipantIDs(ids...)
	return _u
}

// RemoveParticipants removes "participants" edges to ConversationParticipant entities.
func (_u *ConversationUpdateOne) RemoveParticipants(v ...*ConversationParticipant) *ConversationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipantIDs(ids...)
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdateOne) Where(ps ...predicate.Conversation) *ConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationUpdateOne) Select(field string, fields ...string) *ConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Conversation entity.
func (_u *ConversationUpdateOne) Save(ctx context.Context) (*Conversation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdateOne) SaveX(ctx context.Context) *Conversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := conversation.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Conversation.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationUpdateOne) sqlSave(ctx context.Context) (_node *Conversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Conversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversation.FieldID)
		for _, f := range fields {
			if !conversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(conversation.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(conversation.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(conversation.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.CanonicalName(); ok {
		_spec.SetField(conversation.FieldCanonicalName, field.TypeString, value)
	}
	if _u.mutation.CanonicalNameCleared() {
		_spec.ClearField(conversation.FieldCanonicalName, field.TypeString)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipantsIDs(); len(nodes) > 0 && !_u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Conversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
